# Generated by Django 4.2.7 on 2023-12-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_genr_tag_story_novel_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
